### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by keizerzilla** [jeffersonmsb/chip-328#1]
Segui o commando de build do arquivo `chip328.c` e o programa não rodou.

`gcc chip328.c chip328lib.c -o chip328 -lglut -lGL -lGLU -I/chip328.c`

Ubuntu 16.04 - gcc 5.4.0 - Kernel 4.15.0

**Comment by jeffbzrr** [comment]
Deve ser algum problema com as bibliotecas do openGL.

Tenta isso:

```
sudo apt-get update
sudo apt-get install libgl1-mesa-dev
sudo apt-get install build-essential
```

**Comment by keizerzilla** [comment]
Os pacotes estavam OK. Rodei o programa usando `valgrind`, um debugger, e encontrei a origem do problema:

``
keizerzilla@souldjah:~/github/chip-328/build$ valgrind --tool=memcheck ./chip328

==5059== Memcheck, a memory error detector

==5059== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.

==5059== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info

==5059== Command: ./chip328

==5059== 

==5059== Invalid read of size 4

==5059==    at 0x54321BA: fread (iofread.c:37)

==5059==    by 0x400DA1: interfaceLoadROM (in /home/keizerzilla/github/chip-328/build/chip328)

==5059==    by 0x401417: main (in /home/keizerzilla/github/chip-328/build/chip328)

==5059==  Address 0x0 is not stack'd, malloc'd or (recently) free'd

``

O problema estava nessa função `interfaceLoadRom()` no arquivo `chip328.c`. Na linha 27 tem:

`rom = fopen("BRIX", "r");`

Aí estava o problema. Eu compilei o projeto numa pasta fora da raiz do projeto, então o emulador não carregou essa ROM pré-pronta. Eu imaginei que ele fosse pedir pra eu escolher a ROM via linha de comando.

Tudo certo, fechando issue!
